### ISSUE TITLE
Context sensitive directives report duplicate resource definitions

### ISSUE THREAD

**Issue by jcpunk** [hercules-team/augeasproviders_apache#1]
Consider the following puppet code:

    apache_directive { 'Disable autoindex in webroot':
      ensure      => present,
      name        => 'Options',
      context     => 'Directory[arg="/var/www/html"]',
      args        => 'FollowSymLinks',
    }
    
    apache_directive { 'Disable autoindex in icons':
      ensure      => present,
      name        => 'Options',
      context     => 'Directory[arg="/var/www/icons"]',
      args        => 'MultiViews FollowSymLinks',
    }

When imported into a node these items report the following error:
`Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Cannot alias Apache_directive[Disable autoindex in icons] to ["Options"] at test.pp:19; resource ["Apache_directive", "Options"] already declared at test.pp:12 at test.pp:19 on node hostname.example.com`

**Comment by raphink** [comment]
Given the Puppet code you list, it is expected that you would get a duplicate resource.

What is required here is a composite namevar, like we already have in [the pg_hba provider](http://augeasproviders.com/documentation/examples.html#pghba-provider) for example.

Ideally, this namevar would take the `name`, `context` and `target` parameters into play, so you can write:

```puppet
apache_directive { 'Options of Directory[arg="/var/www/html"]':
  ensure      => present,
  args        => 'FollowSymLinks',
}

apache_directive { 'Options of Directory[arg="/var/www/icons"]':
  ensure      => present,
  args        => 'MultiViews FollowSymLinks',
}
```

See also [this PR](https://github.com/hercules-team/augeasproviders_ssh/pull/5/files) for another example of composite namevar implementation.

**Comment by jcpunk** [comment]
Closing issue, moving to https://github.com/hercules-team/augeasproviders_apache/pull/2
